version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - rm -rf package-search search_photo.zip
      - mkdir -p package-search
      - pip install opensearch-py requests requests-aws4auth -t package-search
      - cp search_photo.py package-search/
      - cd package-search
      - zip -r ../search_photo.zip .
      - cd ..
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search_photo.zip --region us-east-1
      - aws lambda wait function-updated --function-name search-photos --region us-east-1
      - aws lambda update-function-configuration --function-name search-photos --runtime python3.12 --handler search_photo.lambda_handler --region us-east-1
      - aws lambda wait function-updated --function-name search-photos --region us-east-1

artifacts:
  files:
    - search_photo.zip
